GET http://localhost:8080/admission/api/applicant_info HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:8080/admission/api/update_payment_status HTTP/1.1
content-type: application/json
Authorization: API_KEY ABCDEF

{
    "gst_roll": "999999",
    "transaction_id": "123456789",
    "payement_method": "paypal",
    "amount": 100
}